use paraflate_core::{PlanningAggression, PredictiveMode, SchedulerPolicy, VerificationMode};

#[derive(Clone, Debug)]
pub struct ModeSpec {
    pub id: &'static str,
    pub label: &'static str,
    pub prediction: PredictiveMode,
    pub verification: VerificationMode,
    pub adaptive: bool,
    pub global_huffman: bool,
    pub scheduler: SchedulerPolicy,
    pub planning: PlanningAggression,
}

pub fn all_modes() -> Vec<ModeSpec> {
    vec![
        ModeSpec {
            id: "m01_standard_create",
            label: "pred_std_verify_after_write_sched_bal_plan_bal_adapt_off_gh_off",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::AfterWrite,
            adaptive: false,
            global_huffman: false,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m02_predictive_off",
            label: "predictive_off",
            prediction: PredictiveMode::Off,
            verification: VerificationMode::AfterWrite,
            adaptive: false,
            global_huffman: false,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m03_predictive_aggressive",
            label: "predictive_aggressive",
            prediction: PredictiveMode::Aggressive,
            verification: VerificationMode::AfterWrite,
            adaptive: false,
            global_huffman: false,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m04_scheduler_throughput_biased",
            label: "scheduler_throughput_biased",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::AfterWrite,
            adaptive: false,
            global_huffman: false,
            scheduler: SchedulerPolicy::ThroughputBiased,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m05_planning_safe",
            label: "planning_safe",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::AfterWrite,
            adaptive: false,
            global_huffman: false,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Safe,
        },
        ModeSpec {
            id: "m06_verification_off",
            label: "verification_off",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::Off,
            adaptive: false,
            global_huffman: false,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m07_verification_strict",
            label: "verification_strict",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::Strict,
            adaptive: false,
            global_huffman: false,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m08_global_huffman_on",
            label: "global_huffman_on",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::AfterWrite,
            adaptive: false,
            global_huffman: true,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m09_adaptive_on_global_huffman_off",
            label: "adaptive_on_gh_off_multi_block",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::AfterWrite,
            adaptive: true,
            global_huffman: false,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
        ModeSpec {
            id: "m10_combo_adapt_gh_verify_strict",
            label: "adaptive_on_global_huffman_on_verify_strict",
            prediction: PredictiveMode::Standard,
            verification: VerificationMode::Strict,
            adaptive: true,
            global_huffman: true,
            scheduler: SchedulerPolicy::Balanced,
            planning: PlanningAggression::Balanced,
        },
    ]
}
